### ISSUE TITLE
Slice solid from offset surfaces 

### ISSUE THREAD

**Issue by yvanblanchard** [aleutgeb/STEPToXSection#3]
Hello,
Is it possible with your lib to slice the input solid with a 3d base surface (not a plane), and get the resulting surface of solid (and contour)? And then repeat with another surface, offset from the base one ?
Thank you

**Comment by aleutgeb** [comment]
Hello,
in the current version you can only slice with a plane and the result contains the line segments of computed contours. In order to fullfill your requirments the program would need some extensions. But the desired functionality should be realizable with OpenCASCADE (https://www.opencascade.com).

**Comment by yvanblanchard** [comment]
Thank you for your reply.
Could you please indicate me the name of OCC operators for doing a solid slice from a 3D surface shape , and also how to offset a surface shape (parallel surface, constant offset) ?
Thank you!

**Comment by aleutgeb** [comment]
1) For offsetting of a surface you can look at the function computeOffsetShape in the file STEPToXSection.cpp. The according OpenCASCADE functionality is in BRepOffsetAPI_MakeOffsetShape (shape to offset could be a single face).
2) Now compute the intersection between the solid and the offsetted shape. This should be doable with the OpenCASCADE functionionality BRepAlgoAPI_Cut (for usage look at computeOffsetShape in the file STEPToXSection.cpp). The result of the cut should be a surface. In order to get the contour you can traverse the edges via TopExp_Explorer using the type TopAbs_EDGE (for usage look at the function convertToWires in the file STEPToXSection.cpp).
