### ISSUE TITLE
Issues with polygon results of multi-slicing

### ISSUE THREAD

**Issue by yvanblanchard** [aleutgeb/STEPToXSection#5]
Hello,

when calling your 'multiple slicing' on the 'bone' test case (with Polygon output type), the final results (in the output .ply file) does not look good: the triangles shared a same vertex/node, leading to triangles edges crossing the 'bone" slice boundary (see image).
I expected to have a kind of delaunay triangulation inside the slice boundary.

![image](https://user-images.githubusercontent.com/63931618/187029674-baca6a13-14e0-492c-bf2f-ed5872f2cd45.png)

![image](https://user-images.githubusercontent.com/63931618/187029717-8d52670d-9121-462d-a36c-d38efae6352e.png)

**Comment by aleutgeb** [comment]
Hello,

currently the command line utility extracts contours using the ply format in the following way. In the case of the format "ply_edges" the ply file contains elements with two vertex indices per element (line segments). In the case of the format "ply_polygons" the ply file contains elements with an arbitrary number of vertex indices per element, where two neighboring vertices represent one line segment of the contour. According to the ply specification (http://paulbourke.net/dataformats/ply) faces with more than three vertices are interpreted in a triangle fan way (center of the fan is always the first vertex). Because our tools use the sequence of vertices only for contour information this is not an issue for us, but 3D viewers will interprete the sequence in a triangle fan way resulting in an erroneous visualization (see your illustration).

Kind regards,
Alex

**Comment by yvanblanchard** [comment]
That's very clear. Thank you Alex
